### ISSUE TITLE
Why the 3d texture seems inverted......

### ISSUE THREAD

**Issue by li19960612** [classner/up#6]
I want to render a image onto 3d model using render.py, but when I change "texture = None" to "texture = texture_image_path" in function "render(model, image, cam, steps, segmented=False, scale=1.)", I found the rendering result is so poor and seems inverted, like this. I use the #5 as my input, texture and pkl. I set flag "segmented" to False.
![0000texture](https://user-images.githubusercontent.com/16774158/43082139-e1a89452-8ec5-11e8-84a3-4e8ebba6eb9e.png)

**Comment by classner** [comment]
Hi!
Concerning the 'poor quality': this is just because the entire image resolution is not very high. It's true that the order channels are inverted (thanks again OpenCV ;-) ): I missed out on that in the first place and kept it that way for legacy reasons. In the case of segmented output, I invert the order manually (see https://github.com/classner/up/blob/master/3dfit/render.py#L175). Just do something similar, or fix it in general in your version of the script...

All the best!

**Comment by li19960612** [comment]
Thank you, it solves my some problems! But I mean the position of texture is inverted. And I probably have passed the problem. In the package "opendr/renderer.py", I commented "data[:,1] = 1.0 - 1.0*data[:,1]", replace "self.vt" to self.camera.r as uv coordinate in function "def mesh_tex_coords(self):"
and the result is like this:
![0000texture](https://user-images.githubusercontent.com/16774158/43176381-fb776760-8ff5-11e8-9d1e-08bebc1e03bb.png)
The quality is still poor but the texture position is correct.
